### ISSUE TITLE
캔버스에 링크 노드 뿌리기

### ISSUE THREAD

**Issue by poetic-form** [DeveloperAcademy-POSTECH/2024-MC3-A02-TeamLongHair#2]
## Description

링크 리스트를 더미로 만들어서 캔버스에 순서대로 뿌릴 예정입니다

## To-do

- [x] 더미 데이터 만들기
- [x] 캔버스에 수평으로 그리기
- [x] 수직으로도 그리기(재귀?)
- [x] 수직으로 그려지면 들여써진만큼 밀리기
